//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompaugesWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompuageRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompuageRole()
        {
            this.Compuages = new HashSet<Compuage>();
        }
    
        public byte Id { get; set; }
        public string Role { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compuage> Compuages { get; set; }
    }
}
