//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompaugesWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadStage
    {
        public int Id { get; set; }
        public string Stage { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
